# Generated by Django 4.0.6 on 2022-07-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Audio',
        ),
    ]
